export const API_BASE_URL = 'http://localhost:8080';

export const ESTABLISHMENT_TYPES = [
  { value: 'Restaurante', label: 'Restaurante' },
  { value: 'Café', label: 'Café' },
  { value: 'Bar', label: 'Bar' },
  { value: 'Hotel', label: 'Hotel' },
  { value: 'Pousada', label: 'Pousada' },
  { value: 'Shopping', label: 'Shopping' },
  { value: 'Supermercado', label: 'Supermercado' },
  { value: 'Farmácia', label: 'Farmácia' },
  { value: 'Hospital', label: 'Hospital' },
  { value: 'Clínica', label: 'Clínica' },
  { value: 'Escola', label: 'Escola' },
  { value: 'Universidade', label: 'Universidade' },
  { value: 'Biblioteca', label: 'Biblioteca' },
  { value: 'Museu', label: 'Museu' },
  { value: 'Teatro', label: 'Teatro' },
  { value: 'Cinema', label: 'Cinema' },
  { value: 'Parque', label: 'Parque' },
  { value: 'Academia', label: 'Academia' },
  { value: 'Banco', label: 'Banco' },
  { value: 'Correios', label: 'Correios' },
  { value: 'Outro', label: 'Outro' },
];

export const ACCESSIBILITY_RATINGS = [
  { value: '1', label: '⭐ 1+' },
  { value: '2', label: '⭐ 2+' },
  { value: '3', label: '⭐ 3+' },
  { value: '4', label: '⭐ 4+' },
  { value: '5', label: '⭐ 5' },
];

export const STATES = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Roraima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' },
];

export const CITIES_BY_STATE: { [key: string]: { value: string; label: string }[] } = {
  AC: [
    { value: 'Rio Branco', label: 'Rio Branco' },
    { value: 'Cruzeiro do Sul', label: 'Cruzeiro do Sul' },
  ],
  AL: [
    { value: 'Maceió', label: 'Maceió' },
    { value: 'Arapiraca', label: 'Arapiraca' },
  ],
  AP: [
    { value: 'Macapá', label: 'Macapá' },
    { value: 'Santana', label: 'Santana' },
  ],
  AM: [
    { value: 'Manaus', label: 'Manaus' },
    { value: 'Parintins', label: 'Parintins' },
  ],
  BA: [
    { value: 'Salvador', label: 'Salvador' },
    { value: 'Feira de Santana', label: 'Feira de Santana' },
    { value: 'Vitória da Conquista', label: 'Vitória da Conquista' },
    { value: 'Camaçari', label: 'Camaçari' },
    { value: 'Itabuna', label: 'Itabuna' },
  ],
  CE: [
    { value: 'Fortaleza', label: 'Fortaleza' },
    { value: 'Caucaia', label: 'Caucaia' },
    { value: 'Juazeiro do Norte', label: 'Juazeiro do Norte' },
    { value: 'Maracanaú', label: 'Maracanaú' },
  ],
  DF: [
    { value: 'Brasília', label: 'Brasília' },
  ],
  ES: [
    { value: 'Vitória', label: 'Vitória' },
    { value: 'Vila Velha', label: 'Vila Velha' },
    { value: 'Serra', label: 'Serra' },
    { value: 'Cariacica', label: 'Cariacica' },
  ],
  GO: [
    { value: 'Goiânia', label: 'Goiânia' },
    { value: 'Aparecida de Goiânia', label: 'Aparecida de Goiânia' },
    { value: 'Anápolis', label: 'Anápolis' },
  ],
  MA: [
    { value: 'São Luís', label: 'São Luís' },
    { value: 'Imperatriz', label: 'Imperatriz' },
    { value: 'São José de Ribamar', label: 'São José de Ribamar' },
  ],
  MT: [
    { value: 'Cuiabá', label: 'Cuiabá' },
    { value: 'Várzea Grande', label: 'Várzea Grande' },
    { value: 'Rondonópolis', label: 'Rondonópolis' },
  ],
  MS: [
    { value: 'Campo Grande', label: 'Campo Grande' },
    { value: 'Dourados', label: 'Dourados' },
    { value: 'Três Lagoas', label: 'Três Lagoas' },
  ],
  MG: [
    { value: 'Belo Horizonte', label: 'Belo Horizonte' },
    { value: 'Uberlândia', label: 'Uberlândia' },
    { value: 'Contagem', label: 'Contagem' },
    { value: 'Juiz de Fora', label: 'Juiz de Fora' },
    { value: 'Betim', label: 'Betim' },
  ],
  PA: [
    { value: 'Belém', label: 'Belém' },
    { value: 'Ananindeua', label: 'Ananindeua' },
    { value: 'Santarém', label: 'Santarém' },
  ],
  PB: [
    { value: 'João Pessoa', label: 'João Pessoa' },
    { value: 'Campina Grande', label: 'Campina Grande' },
    { value: 'Santa Rita', label: 'Santa Rita' },
  ],
  PR: [
    { value: 'Curitiba', label: 'Curitiba' },
    { value: 'Londrina', label: 'Londrina' },
    { value: 'Maringá', label: 'Maringá' },
    { value: 'Ponta Grossa', label: 'Ponta Grossa' },
    { value: 'Cascavel', label: 'Cascavel' },
  ],
  PE: [
    { value: 'Recife', label: 'Recife' },
    { value: 'Jaboatão dos Guararapes', label: 'Jaboatão dos Guararapes' },
    { value: 'Olinda', label: 'Olinda' },
    { value: 'Caruaru', label: 'Caruaru' },
  ],
  PI: [
    { value: 'Teresina', label: 'Teresina' },
    { value: 'Parnaíba', label: 'Parnaíba' },
  ],
  RJ: [
    { value: 'Rio de Janeiro', label: 'Rio de Janeiro' },
    { value: 'São Gonçalo', label: 'São Gonçalo' },
    { value: 'Duque de Caxias', label: 'Duque de Caxias' },
    { value: 'Nova Iguaçu', label: 'Nova Iguaçu' },
    { value: 'Niterói', label: 'Niterói' },
  ],
  RN: [
    { value: 'Natal', label: 'Natal' },
    { value: 'Mossoró', label: 'Mossoró' },
    { value: 'Parnamirim', label: 'Parnamirim' },
  ],
  RS: [
    { value: 'Porto Alegre', label: 'Porto Alegre' },
    { value: 'Caxias do Sul', label: 'Caxias do Sul' },
    { value: 'Pelotas', label: 'Pelotas' },
    { value: 'Canoas', label: 'Canoas' },
    { value: 'Santa Maria', label: 'Santa Maria' },
  ],
  RO: [
    { value: 'Porto Velho', label: 'Porto Velho' },
    { value: 'Ji-Paraná', label: 'Ji-Paraná' },
  ],
  RR: [
    { value: 'Boa Vista', label: 'Boa Vista' },
  ],
  SC: [
    { value: 'Florianópolis', label: 'Florianópolis' },
    { value: 'Joinville', label: 'Joinville' },
    { value: 'Blumenau', label: 'Blumenau' },
    { value: 'São José', label: 'São José' },
  ],
  SP: [
    { value: 'São Paulo', label: 'São Paulo' },
    { value: 'Guarulhos', label: 'Guarulhos' },
    { value: 'Campinas', label: 'Campinas' },
    { value: 'São Bernardo do Campo', label: 'São Bernardo do Campo' },
    { value: 'Santo André', label: 'Santo André' },
    { value: 'Osasco', label: 'Osasco' },
    { value: 'São José dos Campos', label: 'São José dos Campos' },
    { value: 'Ribeirão Preto', label: 'Ribeirão Preto' },
    { value: 'Sorocaba', label: 'Sorocaba' },
  ],
  SE: [
    { value: 'Aracaju', label: 'Aracaju' },
    { value: 'Nossa Senhora do Socorro', label: 'Nossa Senhora do Socorro' },
  ],
  TO: [
    { value: 'Palmas', label: 'Palmas' },
    { value: 'Araguaína', label: 'Araguaína' },
  ],
};

